security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:9191/oauth/authorize
      access-token-uri: http://localhost:9191/oauth/token
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
      user-info-uri:
server:
  servlet:
    session:
      cookie:
        name: KSESSION

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 30      # interval in seconds for heartbeat to Eurekea server
    leaseExpirationDurationInSeconds: 90   # Time before server will remove client if not heartbeat received.
    metadata-map:
      zone: zone12
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5