spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentcloud_vehicle?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
