##  This is the config the we run profile-service with the config server.
#spring:
#  application:
#    name: profile
#  jpa:
#    hibernate:
#      ddl-auto: update

### Without config server
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentcloud_customer?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update


## Confirm where security service is running.
#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:9191/oauth/check_token
#    client:
#      client-id: mobile   # same as auth server
#      client-secret: pin
