spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  datacenter: CapeTown
  environment: Production
  #  environment: production
