spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  application:
    name: task
