server:
  port: 8191
application:
  name: config-server

# Enable scanning of all directories that contains *service in the name.
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kappaj2/rentalstoreconfig
          search-paths:
            - 'service-config/*service'  # This will search for all ending in 'service'
            - 'service-config/*server'
          timeout: 10
# Call the api as follows to get a yml properties
# http://localhost:8191/jdbc-auth-server/dev
#                       service         / profile
# Get the exact property file data
# http://localhost:8191/jdbc-auth-server-dev.yml
# http://localhost:8191/jdbc-auth-server-dev.properties
# http://localhost:8191/jdbc-auth-server-dev.json